//
// Created by Maikol Guzman Alan on 6/20/22.
//

#ifndef PARTIAL_TEST_3_COLEGIADO_SOLUCION_ANALISISTIPO_H
#define PARTIAL_TEST_3_COLEGIADO_SOLUCION_ANALISISTIPO_H

enum class AnalisisTipo {ANALISIS_ENFERMEDADES, ANALISIS_BASE_NITROGENADA, ANALISIS_CONCORDANCIA};

#endif //PARTIAL_TEST_3_COLEGIADO_SOLUCION_ANALISISTIPO_H
