//
// Created by Maikol Guzman Alan on 6/21/22.
//

#include "../src/ArchivoManager.h"
#include "../lib/catch2/catch.hpp"
#include "ArchivoManager.h"

// Descomentar el bloque siguiente para autoevaluación, la ejecución correcta de esta prueba le genera los puntos
// Hacer commit de la prueba sin el bloque comentado


TEST_CASE("Procesamiento correcto de los pacientes", "[CargaPacientes]") {
    ArchivoManager archivoManager;
    string archivoPacientes = "files/pacientes.txt";
    vector<Paciente> pacientes = archivoManager.cargarPacientes(archivoPacientes);

    REQUIRE(pacientes.size() == 10);
    REQUIRE(pacientes[0].getId() == "27514443699");
    REQUIRE(pacientes[0].getNombre() == "Felix Reese");
    REQUIRE(pacientes[0].getTelefono() == "1-529-679-8391");
    REQUIRE(pacientes[0].getCorreo() == "auctor.quis.tristique@sitametfaucibus.org");
    REQUIRE(pacientes[0].getSecuencia() == "GGGGCATCCTGGGCCCAATCGCACATTCCAGGGAGGGATACCAGGGGCGTCGAGGGGCCGGCAAAGCGGAGGGAAAGCCTCTCGAGGCGGACTAGTGCCGCGCGCTGTCCGACCAAGGAACCTAAACAGTATTGGGTGAGGTGGCAAAGATCAGCAATGCAACAAGCAATGTGGGAGCGCTCGTAATGAAAACAGCAAAGCCACCCAGGGGATCGGGGCGACGTGAGCTAAACTGCATGTGTACCAGAAACTACCGCCCAGTATGTCTGATATGAACCAAACGACGACGCAACCCGCGCAAGGATGGAAAGAGGCCTGAGATCCGCACCCCGCAGGGGCACTAAAGCACCCTAACAAAGAGCACTGCAAAAATTGGCTAGCATAATACCATTTGATTAAGTAGCCCGCATTTGCACATCTGCCAGTGGACAGGCGCGCCTAGAACGCGGTCGTCACCATGAACGCGCCGACCGGCTTATGCGGACAGCGTAGCCATTGGGCGAGTAGCACGGTTCAGGGCGAATGAACAGTAGTGAAGACTGAGAAGCCCTCGAAAACTAAAAAGAACAGCGTTGAGTACTGCGAACGCGATATGAACGGATGCCAAAAACAGCAGACTCTATGGCAATATGCCAGGCGGACGAGTCTATAACTCCTGAGGCATCGAAGAGGGAACGCAAGCAACCTCTGACCGACGTTACCAAGGAGTGCCGTAGATATAGAAAACGCGGCAGGCAGGTTGGACGTTCAAGTGTCGTTGAGTAGCCGAACAGACCCGGTGCCAAGTTTAGGGGAAATAAAAATCAGCCCGCCCCGTCGCAAATTGGAGGAGAAGCGCACGCCCGGTTAACAATCGAATCGGGCCAGGGCGAGACACCCGAGGTCACCCGCAAACATAACACCTTTCATCAGAAGAGCGTCGCGAAGCCCGTGCGATGGGCCGACACAGTGCTATATCCATTGCTGTGGAGGTCTCAGATGAAAAGCAAGGACGTCGCAGCGCGGATCTACAAAAGGCATACCCCAGATATTTACAGTAGAGAGAGTCACATCAGCCCAGCGGCGACCGTGCAGATGTGTACCGCGCCACCGGTGTAAATGCTCGCACAACAACGGGCACGCCGTAAGGAGGAGTGTACTAGTACAATTACAGGCATCCGGGCAAATGAGCAGAAAACCACAGGCCAAGGAGAAACGGATGGGAATTCAGAGAACAATTTGAGGGAAGCTGTCGCCGGACGCCGGGTCAACCTGTACCATCAATGCGGGGGGGGGCGTTTCTAAAAGACGAAAAAGAGCCGCTGATCTTGAAGCGCACGACCGGTCGGCCTCTAGGAAAACCTGTCAGACACTGCTCGGCGGCTGGAAGTCAAGAGGCGTCACGCGAAGGCAGATGCGGTAGACACGACCATGACTCGTAACGTCCAAACCCAAGGAAAGCTAGGATGAAAGCCTCGATGGGCGAAGCAGGATGGAGCGCTGCAAGGGCGAAGCAACAGAAAGCGGAGAGCGGAGTAGGCAATTCAGTGTTGCCCGCTCGCGAGAGGGCTCCCAAGACAATGCGTACACAATGGGAGGAATGACTGCTTGCTCGAGGAAAACAAAACCTCCTAAAGAGCTTAGCCTGGTAATAGGAAATGTGTGTCTGCACGAGAAA");
    REQUIRE(pacientes[9].getId() == "87759707299");
    REQUIRE(pacientes[9].getNombre() == "Branden Fox");
    REQUIRE(pacientes[9].getTelefono() == "1-750-210-9300");
    REQUIRE(pacientes[9].getCorreo() == "sit@turpisnecmauris.ca");
    REQUIRE(pacientes[9].getSecuencia() == "CTAGTTTGGGGAACGAACATGAGTAGCGGATTTAAATCTGGCTGTACGCCCCACTGTGACGGTAGGGGTGAACGCGGAATGCTACGTTCGAAACCCAGTAAACAAAAGCGAACGGGAAATACTCCGAGGGGGTACATTGTGTGAGAAAAAGATTCGCCCCCGGGCTTCGAGGAAAGAAGACGATGGCACGGGGACGGAAGACGAACCCCGGTTGTCATAGGGGGACCGTTGTCAGTGAACCTAAACTGCATTGCAACCGGGACTCCTGACGAGATAGAGACAAATCAAAGATTCGTAATCGCTGGCTTCGCCGTTCCCACGGGAAGGTCAACAAGGAGCGGGGGGGCGGATCCATTGCAGACCACGGGCGTCAACGTCTGGATGGCAAGGACCATGGAACGTGTGACTATGACTAGTTCCCTTACCATCCGCAGTCCGCCCAATACGTGCCAATGCGGAGCACAAAGAGCCAATGATAAAATTGAACGTTGAGAAATCGAGCTGAGCGGGCGGGAACTGGGCGCCGATGTCACACCCCAATGCCAGCACACCGGCAAACCCGACATCACACCCTAGAGAATAGAAGATACGCCAAAGAAGCGTAAGGCTAGCTCTGACGTAGCGGGGACGGCAAAGACAGTGGCTCTCCTAGGGTAATCGGTAGCATTGGTGCGCCGGCTGGCAGGGAGGCATCACAATGCTGCAAATGCTGTAGGTGCCCTGCTCCGACACAATGGCCTACGAAGAGTTAAAGGCTTCAGCACAATGATCCATCCACTGCAGCATAAAGCCCTCACGGAGACACTCCAAGGGGGCGAATGAGGGCAGGTGTAGTAGCGCGTCGGACGGCCGCGAGCCGAGACGACCCAAGATACGGTGTGTCCGGCCTGCATATTAGTAGCGAACAAAATTGCGGCAGAGCCTGTTCCCCGAGTCCCGCTAGCCGACAGGGGAGCATCCCAAAGTGTGATGGATACAATCCTTGCCCAAGGCAAGTCAGCGCGACGCCAGCGACTTGGCACAAAGGCCGGCTCAACAGAATACTGAGTAGATAGAGTACCGAAATGAGAGAGGACTTGCCACGCTAACCGCCCGAGTATAATTCGCGAAAGATGCGGCAGGGATTTTGGGAACACTGTGCTATAGCTCGCGACAGCTCAAGGACAGAGGACATCCGCATCACTCGAACAACCACGGATGAAGAGAGGGCCGAGGTCACGATCTCGCTGAACGAGAAGCTTAAAAAACCGACCCAAGGACTAGAGGAAGGGATAAGGTTAGAGTGTGGCAACCGGCACAATCGCGCTAACTAGGAGAGCACGGCTAGATATAGGGGAGGCGGAAGTACGCGAGCGCCGAATCCCAAGCCTGAGATAACAAAGCCAGAGGCAATGGTGTCTTAGTCGCGAAAGCCAAACAAACGAAAAATCACAAAGGGGGGTCTCTCCGATTCAGAGAAGAAAACCGACCCAAGGTGTACGGAGGATGGTACGCCGAGCCGGAACGGAAAAAAAGGGGAATCCCCTACTAGAGACAGAAAAAAACGCCGCGAAGGACC");

}

TEST_CASE("Excepción en el código", "[CargaPacientesError]") {
    ArchivoManager archivoManager;
    string archivoPacientes = "noexiste.txt";

    REQUIRE_THROWS_AS(archivoManager.cargarPacientes(archivoPacientes), std::exception);
    REQUIRE_THROWS_MATCHES(archivoManager.cargarPacientes(archivoPacientes), std::exception,
                           Catch::Message("Could not open the file [noexiste.txt]"));
}

