# Makefile created by Maikol Guzmán Alán
# No modificar este archivo. Se utiliza para el autograde

CXX 			= g++
CPPFLAGS 		= -std=c++11
TEST_SOURCES 	= tst/main.cpp tst/01_ServicioTest.cpp tst/02_GrupoTest.cpp tst/03_CoordinadorTest.cpp tst/04_ZonaTest.cpp tst/05_CalculosTest.cpp
SOURCES 		= src/Grupo.cpp src/Persona.cpp src/Region.cpp src/Servicio.cpp src/Zona.cpp

all: a.out

a.out:
	$(CXX) $(CPPFLAGS) $(SOURCES) $(TEST_SOURCES)

Servicio_1: a.out
	./a.out "[Servicio_1]"

Servicio_2: a.out
	./a.out "[Servicio_2]"

Servicio_3: a.out
	./a.out "[Servicio_3]"

Grupo_1: a.out
	./a.out "[Grupo_1]"

Grupo_2: a.out
	./a.out "[Grupo_2]"

Coordinador: a.out
	./a.out "[Coordinador]"

Zona_1: a.out
	./a.out "[Zona_1]"

Zona_2: a.out
	./a.out "[Zona_2]"

Calculo_1: a.out
	./a.out "[Calculo_1]"

Calculo_2: a.out
	./a.out "[Calculo_2]"

Calculo_3: a.out
	./a.out "[Calculo_3]"

Calculo_4: a.out
	./a.out "[Calculo_4]"

Calculo_5: a.out
	./a.out "[Calculo_5]"

Calculo_6: a.out
	./a.out "[Calculo_6]"

clean:
	rm a.out